spring.application.name=arena-websocket-echo
server.address=127.0.0.1
server.port=8080
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=5s
spring.web.resources.cache.cachecontrol.no-store=true
